language: node_js
sudo: required
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
node_js:
- '16'
install:
  - npm ci
before_script:
  - npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
script:
  # build internally used tsc script while it is private package
  - ./node_modules/.bin/tsc -p packages/tsc-transform-imports/
  - npm run lint
  - npm run test:ci
