name: Frontend components CI pipeline
on:
  pull_request:
    branches:
      - master
      - nx
  push:
    branches:
      - master
      - nx

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cache'
      - uses: './.github/actions/cypress-cache'
      - name: Install dependencies
        run: npm i
  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cache'
      - name: Build
        run: npm run build
  unit-test:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cache'
      - name: Run unit tests
        run: npm run test:unit
  component-test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cache'
      - uses: './.github/actions/cypress-cache'
      - name: Install deps
        shell: bash
        run: npm i
      - name: Run component tests
        uses: cypress-io/github-action@v6
        with:
          command: npx nx affected -t test:component --exclude=demo --configuration=ci --parallel=1
  lint: 
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: './.github/actions/cache'
      - name: Lint
        run: npx nx affected -t test:lint --exclude=demo
